# Generated by Django 3.2.12 on 2022-03-28 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField()),
                ('glide_number', models.TextField(blank=True, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_accuracy', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_accuracy', models.TextField(blank=True, null=True)),
                ('hazard_category', models.TextField(blank=True, null=True)),
                ('hazard_sub_category', models.TextField(blank=True, null=True)),
                ('hazard_sub_type', models.TextField(blank=True, null=True)),
                ('hazard_type', models.TextField(blank=True, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('new_displacement_source', models.TextField(blank=True, null=True)),
                ('new_displacement_since', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_disaster', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Disaster',
                'verbose_name_plural': 'Disasters',
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField()),
                ('total_displacement', models.BigIntegerField(blank=True, null=True)),
                ('total_displacement_source', models.TextField(blank=True, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('new_displacement_source', models.TextField(blank=True, null=True)),
                ('returns', models.BigIntegerField(blank=True, null=True)),
                ('returns_source', models.TextField(blank=True, null=True)),
                ('local_integration', models.BigIntegerField(blank=True, null=True)),
                ('local_integration_source', models.TextField(blank=True, null=True)),
                ('resettlement', models.BigIntegerField(blank=True, null=True)),
                ('resettlement_source', models.TextField(blank=True, null=True)),
                ('cross_border_flight', models.BigIntegerField(blank=True, null=True)),
                ('cross_border_flight_source', models.TextField(blank=True, null=True)),
                ('children_born_to_idps', models.BigIntegerField(blank=True, null=True)),
                ('children_born_to_idps_source', models.TextField(blank=True, null=True)),
                ('idp_deaths', models.BigIntegerField(blank=True, null=True)),
                ('idp_deaths_source', models.TextField(blank=True, null=True)),
                ('total_displacement_since', models.TextField(blank=True, null=True)),
                ('new_displacement_since', models.TextField(blank=True, null=True)),
                ('returns_since', models.TextField(blank=True, null=True)),
                ('resettlement_since', models.TextField(blank=True, null=True)),
                ('local_integration_since', models.TextField(blank=True, null=True)),
                ('cross_border_flight_since', models.TextField(blank=True, null=True)),
                ('children_born_to_idps_since', models.TextField(blank=True, null=True)),
                ('idp_deaths_since', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_conflict', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflicts',
            },
        ),
    ]
