# Generated by Django 3.2.12 on 2022-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_conflict_disaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryadditionalinfo',
            name='year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='idmc_region',
            field=models.CharField(blank=True, choices=[('caribbean', 'Caribbean'), ('south_east_asia', 'South-East Asia'), ('southern_europe', 'Southern Europe'), ('east_asia', 'East Asia'), ('north_america', 'North America'), ('south_asia', 'South Asia'), ('latin_america', 'Latin America'), ('western_africa', 'Western Africa'), ('micronesia', 'Micronesia'), ('horn_of_africa', 'Horn of Africa'), ('north_west_and_central_europe', 'North, West and Central Europe'), ('melanesia', 'Melanesia'), ('eastern_europe', 'Eastern Europe'), ('australia_and_nz', 'Australia and NZ'), ('central_africa', 'Central Africa'), ('polynesia', 'Polynesia'), ('northern_africa', 'Northern Africa'), ('central_asia', 'Central Asia'), ('western_asia', 'Western Asia'), ('southern_africa', 'Southern Africa'), ('asia', 'Asia'), ('southern_asia', 'Southren asia'), ('europe', 'Europe'), ('europe_and_central_asia', 'Europe and southern asia'), ('africa', 'Africa'), ('middle_east_and_north_africa', 'Middle east and north africa'), ('oceania', 'oceania'), ('east_asia_and_pacific', 'East asia and pacific'), ('high_income_non_oecd_member', 'high income non oecd member'), ('sub_saharan_africa', 'Sub saharan africa'), ('middle_africa', 'middle africa'), ('americas', 'Americas'), ('high_income_oecd_member', 'high income oecd member'), ('latin_america_and_the_caribbean', 'latin america and the caribbean'), ('south_america', 'South america'), ('australia_and_new_zealand', 'Australia and new zealand'), ('western_europe', 'Western europe'), ('central_america', 'Central america'), ('northern_america', 'northern america'), ('south_eastern_asia', 'South eastern asia'), ('eastern_africa', 'Eastern africa'), ('eastern_asia', 'Eastern asia'), ('northern_europe', 'Northern europe')], max_length=100, null=True, verbose_name='Idmc region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='idmc_sub_region',
            field=models.CharField(blank=True, choices=[('caribbean', 'Caribbean'), ('latin_america', 'Latin America'), ('middle_east', 'Middle East'), ('south_caucasus', 'South caucasus')], max_length=100, null=True, verbose_name='Idmc sub region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='united_nations_region',
            field=models.CharField(blank=True, choices=[('caribbean', 'Caribbean'), ('south_east_asia', 'South-East Asia'), ('southern_europe', 'Southern Europe'), ('east_asia', 'East Asia'), ('north_america', 'North America'), ('south_asia', 'South Asia'), ('latin_america', 'Latin America'), ('western_africa', 'Western Africa'), ('micronesia', 'Micronesia'), ('horn_of_africa', 'Horn of Africa'), ('north_west_and_central_europe', 'North, West and Central Europe'), ('melanesia', 'Melanesia'), ('eastern_europe', 'Eastern Europe'), ('australia_and_nz', 'Australia and NZ'), ('central_africa', 'Central Africa'), ('polynesia', 'Polynesia'), ('northern_africa', 'Northern Africa'), ('central_asia', 'Central Asia'), ('western_asia', 'Western Asia'), ('southern_africa', 'Southern Africa'), ('asia', 'Asia'), ('southern_asia', 'Southren asia'), ('europe', 'Europe'), ('europe_and_central_asia', 'Europe and southern asia'), ('africa', 'Africa'), ('middle_east_and_north_africa', 'Middle east and north africa'), ('oceania', 'oceania'), ('east_asia_and_pacific', 'East asia and pacific'), ('high_income_non_oecd_member', 'high income non oecd member'), ('sub_saharan_africa', 'Sub saharan africa'), ('middle_africa', 'middle africa'), ('americas', 'Americas'), ('high_income_oecd_member', 'high income oecd member'), ('latin_america_and_the_caribbean', 'latin america and the caribbean'), ('south_america', 'South america'), ('australia_and_new_zealand', 'Australia and new zealand'), ('western_europe', 'Western europe'), ('central_america', 'Central america'), ('northern_america', 'northern america'), ('south_eastern_asia', 'South eastern asia'), ('eastern_africa', 'Eastern africa'), ('eastern_asia', 'Eastern asia'), ('northern_europe', 'Northern europe')], max_length=100, null=True, verbose_name='United nations region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='wb_region',
            field=models.CharField(blank=True, choices=[('caribbean', 'Caribbean'), ('south_east_asia', 'South-East Asia'), ('southern_europe', 'Southern Europe'), ('east_asia', 'East Asia'), ('north_america', 'North America'), ('south_asia', 'South Asia'), ('latin_america', 'Latin America'), ('western_africa', 'Western Africa'), ('micronesia', 'Micronesia'), ('horn_of_africa', 'Horn of Africa'), ('north_west_and_central_europe', 'North, West and Central Europe'), ('melanesia', 'Melanesia'), ('eastern_europe', 'Eastern Europe'), ('australia_and_nz', 'Australia and NZ'), ('central_africa', 'Central Africa'), ('polynesia', 'Polynesia'), ('northern_africa', 'Northern Africa'), ('central_asia', 'Central Asia'), ('western_asia', 'Western Asia'), ('southern_africa', 'Southern Africa'), ('asia', 'Asia'), ('southern_asia', 'Southren asia'), ('europe', 'Europe'), ('europe_and_central_asia', 'Europe and southern asia'), ('africa', 'Africa'), ('middle_east_and_north_africa', 'Middle east and north africa'), ('oceania', 'oceania'), ('east_asia_and_pacific', 'East asia and pacific'), ('high_income_non_oecd_member', 'high income non oecd member'), ('sub_saharan_africa', 'Sub saharan africa'), ('middle_africa', 'middle africa'), ('americas', 'Americas'), ('high_income_oecd_member', 'high income oecd member'), ('latin_america_and_the_caribbean', 'latin america and the caribbean'), ('south_america', 'South america'), ('australia_and_new_zealand', 'Australia and new zealand'), ('western_europe', 'Western europe'), ('central_america', 'Central america'), ('northern_america', 'northern america'), ('south_eastern_asia', 'South eastern asia'), ('eastern_africa', 'Eastern africa'), ('eastern_asia', 'Eastern asia'), ('northern_europe', 'Northern europe')], max_length=100, null=True, verbose_name='Wb region'),
        ),
    ]
