# Generated by Django 3.2.12 on 2022-03-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20220328_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_conflict', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_disaster', to='country.country', verbose_name='Country'),
        ),
    ]
