# Generated by Django 3.2.12 on 2022-03-29 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20220328_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='countryadditionalinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_additonal_info', to='country.country', verbose_name='Country'),
        ),
    ]
