# Generated by Django 3.2.13 on 2022-04-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20220329_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryadditionalinfo',
            options={'verbose_name': 'Country additional information', 'verbose_name_plural': 'Country additional informations'},
        ),
        migrations.AddField(
            model_name='country',
            name='background_image',
            field=models.FileField(blank=True, upload_to='countries/'),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, verbose_name='Country description'),
        ),
        migrations.AddField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country title'),
        ),
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Country description')),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_overviews', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country overview',
                'verbose_name_plural': 'Country overviews',
            },
        ),
        migrations.CreateModel(
            name='EssentialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Essential link')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_essential_links', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country essential link',
                'verbose_name_plural': 'Country essential links',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='contact_person/')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name of contact person')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation of contact person')),
                ('email', models.CharField(max_length=255, verbose_name='Email of contact person')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_contact_persons', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country contact person',
                'verbose_name_plural': 'Country contact persons',
            },
        ),
    ]
