# Generated by Django 3.2.13 on 2022-05-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20220422_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AddField(
            model_name='essentiallink',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AddField(
            model_name='overview',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
    ]
