# Generated by Django 3.2.13 on 2022-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20220504_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiallink',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
