# Generated by Django 3.2.13 on 2022-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_essentiallink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='essentiallink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='essentiallink',
            name='title',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='essentiallink',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
