# Generated by Django 3.2.13 on 2022-05-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_auto_20220509_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_contact_persons', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Country description'),
        ),
        migrations.AlterField(
            model_name='essentiallink',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_essential_links', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='essentiallink',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Country description'),
        ),
    ]
