# Generated by Django 3.2.13 on 2022-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_auto_20220509_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='internal_displacement_description',
            field=models.TextField(blank=True, null=True, verbose_name='Internal displacement description'),
        ),
        migrations.AddField(
            model_name='country',
            name='latest_new_displacements_description',
            field=models.TextField(blank=True, null=True, verbose_name='Latest new displacements description'),
        ),
    ]
