# Generated by Django 3.2.13 on 2022-05-10 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_auto_20220509_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='bounding_box',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None, verbose_name='Bounding Box'),
        ),
    ]
