# Generated by Django 3.2.13 on 2022-05-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_country_bounding_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='displacement_data_description',
            field=models.TextField(blank=True, null=True, verbose_name='Displacement data description'),
        ),
    ]
