# Generated by Django 3.2.13 on 2022-05-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_country_displacement_data_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='latest_new_displacements_description',
        ),
    ]
