# Generated by Django 3.2.13 on 2022-05-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_auto_20220518_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshotfile',
            options={'verbose_name': 'Snapshot file', 'verbose_name_plural': 'Snapshot files'},
        ),
    ]
