# Generated by Django 3.2.13 on 2022-06-07 04:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0018_country_good_practice_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='center_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None, verbose_name='Center point'),
        ),
    ]
