# Generated by Django 3.2.13 on 2022-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_country_center_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='idmc_region',
            field=models.CharField(blank=True, choices=[('australia_and_nz', 'Australia and NZ'), ('caribbean', 'Caribbean'), ('central_africa', 'Central Africa'), ('central_asia', 'Central Asia'), ('east_asia', 'East Asia'), ('eastern_europe', 'Eastern Europe'), ('horn_of_africa', 'Horn of Africa'), ('latin_america', 'Latin America'), ('melanesia', 'Melanesia'), ('micronesia', 'Micronesia'), ('north_america', 'North America'), ('northern_africa', 'Northern Africa'), ('north_west_and_central_europe', 'North, West and Central Europe'), ('polynesia', 'Polynesia'), ('south_asia', 'South Asia'), ('south_east_asia', 'South-East Asia'), ('southern_africa', 'Southern Africa'), ('southern_europe', 'Southern Europe'), ('western_africa', 'Western Africa'), ('western_asia', 'Western Asia')], max_length=100, null=True, verbose_name='Idmc region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='united_nations_region',
            field=models.CharField(blank=True, choices=[('asia', 'Asia'), ('southern_asia', 'Southren asia'), ('europe', 'Europe'), ('europe_and_central_asia', 'Europe and southern asia'), ('africa', 'Africa'), ('oceania', 'oceania'), ('sub_saharan_africa', 'Sub saharan africa'), ('middle_africa', 'middle africa'), ('americas', 'Americas'), ('latin_america_and_the_caribbean', 'latin america and the caribbean'), ('south_america', 'South america'), ('australia_and_new_zealand', 'Australia and new zealand'), ('western_europe', 'Western europe'), ('central_america', 'Central america'), ('northern_america', 'northern america'), ('south_eastern_asia', 'South eastern asia'), ('eastern_africa', 'Eastern africa'), ('eastern_asia', 'Eastern asia'), ('northern_europe', 'Northern europe')], max_length=100, null=True, verbose_name='United nations region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='wb_region',
            field=models.CharField(blank=True, choices=[('east_asia_and_pacific', 'East asia and pacific'), ('europe_and_central_asia', 'Europe and Central Asia'), ('high_income_oecd_member', 'high income oecd member'), ('high_income_non_oecd_member', 'high income non oecd member'), ('latin_america_and_the_caribbean', 'Latin America and the Caribbean'), ('middle_east_and_north_africa', 'Middle east and north africa'), ('south_asia', 'South Asia'), ('sub_saharan_africa', 'Sub-Saharan Africa')], max_length=100, null=True, verbose_name='Wb region'),
        ),
    ]
