# Generated by Django 4.1.4 on 2022-12-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_figureanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figureanalysis',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figure_analysis', to='country.country', verbose_name='Country'),
        ),
    ]
