# Generated by Django 4.1.5 on 2023-04-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0024_alter_figureanalysis_year_alter_overview_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='country',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='figureanalysis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='figureanalysis',
            name='country',
        ),
        migrations.DeleteModel(
            name='SnapshotFile',
        ),
        migrations.DeleteModel(
            name='Conflict',
        ),
        migrations.DeleteModel(
            name='Disaster',
        ),
        migrations.DeleteModel(
            name='FigureAnalysis',
        ),
    ]
