# Generated by Django 4.1.5 on 2024-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0025_remove_conflict_country_remove_disaster_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='year'),
        ),
    ]
