version: '3.2'

services:
  # olddb:  # TODO: Remove this
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_DB=${LEGACY_POSTGRES_DB}
  #     - POSTGRES_USER=${LEGACY_POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${LEGACY_POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres-data-old:/var/lib/postgresql/data

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    restart: always
    image: gidd-server/server
    build:
      context: ./
    tty: true
    environment:
      DEBUG:
      SECRET_KEY:
      CORS_ALLOWED_ORIGINS:
      # Current DB
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      # # Old DB TODO: Remove
      # LEGACY_POSTGRES_NAME: ${LEGACY_POSTGRES_NAME:-postgres}
      # LEGACY_POSTGRES_USER: ${LEGACY_POSTGRES_USER:-postgres}
      # LEGACY_POSTGRES_PWD: ${LEGACY_POSTGRES_PWD:-postgres}
      # LEGACY_POSTGRES_HOST: ${LEGACY_POSTGRES_HOST:-olddb}
      # LEGACY_POSTGRES_PORT: ${LEGACY_POSTGRES_PORT:5433}
      # # Misc
      # ENABLE_MIGRATION: ${ENABLE_MIGRATION:-False}
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./:/code
      - media:/media
    ports:
      - '7000:7000'
    depends_on:
      - db
      # - olddb

volumes:
  media:
  postgres-data:
  # postgres-data-old:
