version: '3.2'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    restart: unless-stopped
    image: gidd-server/server
    build:
      context: ./
    tty: true
    environment:  # NOTE: .env is used to fill this values
      GIDD_ENVIRONMENT: "DEVELOPMENT"
      DEBUG:
      SECRET_KEY:
      CORS_ALLOWED_ORIGINS:
      CSRF_TRUSTED_ORIGINS:
      # Current DB
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      # AWS
      AWS_TRANSLATE_ACCESS_KEY:
      AWS_TRANSLATE_SECRET_KEY:
      AWS_TRANSLATE_REGION:
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./:/code
      - media:/media
    ports:
      - '7000:7000'
    depends_on:
      - db

volumes:
  media:
  postgres-data:
  redis-data:
