version: '3.2'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: $DOCKER_IMAGE_SERVER
    environment:
      CI: "true"
      # https://github.com/pytest-dev/pytest/issues/7443
      PYTEST_ADDOPTS: "--color=yes"
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      CSRF_TRUSTED_ORIGINS: http://localhost:3000
      DEBUG: "true"
      SECRET_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
      EMAIL_FROM: dev.gidd.org
      # From db.environment
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - ./coverage/:/code/coverage/
      - ./ci-share/:/ci-share/
    depends_on:
      - db
