[tool.poetry]
name = "gidd-server"
version = "1.0"
description = "GIDD server"
authors = ["dev <dev.togglecorp.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^3.2.10"
django-environ = "^0.8.1"
psycopg2 = "^2.9.3"
django-cors-headers = "==3.7.0"

[tool.poetry.dev-dependencies]
pytest-profiling = "*"
pytest-ordering = "*"
pytest-django = "*"
pytest-icdiff = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
