# Generated by Django 3.2.13 on 2022-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('good_practice_listing_page', 'Good practice listing page'), ('submit_good_practice', 'Submit good practice'), ('good_practice_cotact_information', 'Good practice cotact information')], max_length=255, verbose_name='Static page type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Static page',
                'verbose_name_plural': 'Static pages',
            },
        ),
    ]
