# Generated by Django 3.2.13 on 2022-05-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='type',
            field=models.CharField(choices=[('good_practice_listing_page', 'Good practice listing page'), ('submit_good_practice', 'Submit good practice'), ('good_practice_contact_information', 'Good practice contact information')], max_length=255, verbose_name='Static page type'),
        ),
    ]
