# Generated by Django 3.2.13 on 2022-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_staticpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
