# Generated by Django 4.1.4 on 2022-12-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221103_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'HOMEPAGE - Introduction and Contact information', 'verbose_name_plural': 'HOMEPAGE - Introduction and Contact information'},
        ),
    ]
