# Generated by Django 3.2.13 on 2022-04-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0009_auto_20220421_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.CreateModel(
            name='GoodPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Good practice type')),
                ('drivers_of_dispalcement', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Driver of displacement')),
                ('trigger', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Trigger')),
                ('dispalcement_impact', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Displacement impact')),
                ('intervention_phase', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Intervention phase')),
                ('stage', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Stage')),
                ('timeframe', models.CharField(choices=[('A', 'Enum A'), ('B', 'Enum B')], max_length=255, verbose_name='Timeframe')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_good_practice', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Good practice',
                'verbose_name_plural': 'Good practices',
            },
        ),
        migrations.CreateModel(
            name='MediaAndResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255, verbose_name='Media and resource link')),
                ('good_practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_essential_links', to='good_practice.goodpractice', verbose_name='Good practice')),
            ],
            options={
                'verbose_name': 'Media and resource link',
                'verbose_name_plural': 'Media and resource links',
            },
        ),
    ]
