# Generated by Django 3.2.13 on 2022-05-04 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0007_auto_20220504_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.CreateModel(
            name='GoodPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('policies_strategies_and_legal_frameworks', 'Policies, strategies and legal frameworks'), ('governance_capacity_and_institutional_set_up', 'Governance capacity and institutional set-up'), ('displacement_monitoring_data_collection_analysis_and_systems', 'Displacement monitoring (data collection, analysis and systems)'), ('risk_reduction_and_prevention', 'Risk Reduction and Prevention (DRR, CCA and peacebuilding)'), ('protection_and_assistance_and_durable_solutions', 'Protection and assistance, and durable solutions')], max_length=255, verbose_name='Good practice type')),
                ('drivers_of_dispalcement', models.CharField(choices=[('slow_onset_disasters', 'Slow onset disasters'), ('sudden_onset_disasters', 'Sudden onset disasters'), ('conflict_and_violence', 'Conflict and violence'), ('development_and_urbanisation', 'Development and urbanisation')], max_length=255, verbose_name='Driver of displacement')),
                ('stage', models.CharField(choices=[('promising', 'Promising'), ('advanced', 'Advanced'), ('successful', 'Successful')], max_length=255, verbose_name='Stage')),
                ('focus_area', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('livelihoods_and_employment', 'Livelihoods and employment'), ('housing_land_and_property', 'Housing, land and property'), ('food_and_water_insecurity', 'Food and water insecurity'), ('social_protection_and_assistance', 'Social protection and assistance'), ('safety_and_security', 'Safety and social security'), ('civic_and_social_rights', 'Civic and social rights'), ('environment', 'Environment'), ('gender', 'Gender'), ('disability', 'Disability'), ('children_and_youth', 'Children and youth')], max_length=255, verbose_name='Stage')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_good_practice', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Good practice',
                'verbose_name_plural': 'Good practices',
            },
        ),
        migrations.CreateModel(
            name='MediaAndResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255, verbose_name='Media and resource link')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('good_practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_essential_links', to='good_practice.goodpractice', verbose_name='Good practice')),
            ],
            options={
                'verbose_name': 'Media and resource link',
                'verbose_name_plural': 'Media and resource links',
            },
        ),
    ]
