# Generated by Django 3.2.13 on 2022-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodpractice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
