# Generated by Django 3.2.13 on 2022-05-24 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0002_alter_goodpractice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpractice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 24, 8, 3, 50, 590677, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='good_practice_form_url',
            field=models.URLField(default=datetime.datetime(2022, 5, 24, 8, 3, 59, 390531, tzinfo=utc), max_length=255, verbose_name='Good practice form URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='image',
            field=models.FileField(blank=True, upload_to='good_practice/', verbose_name='Good practices'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
