# Generated by Django 3.2.13 on 2022-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0004_auto_20220525_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpractice',
            name='end_year',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='End year'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='media_and_resource_links',
            field=models.TextField(blank=True, null=True, verbose_name='Media and resource links'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='page_viewed_count',
            field=models.BigIntegerField(default=0, verbose_name='Total page viewed count'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='start_year',
            field=models.BigIntegerField(default=2022, verbose_name='Start year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='drivers_of_dispalcement',
            field=models.CharField(choices=[('increasing_temperatures_drought_and_desertification', 'Increasing temperatures, drought, and desertification'), ('land_forest_degradation_and_loss_of_biodiversity', 'Land/forest degradation and loss of biodiversity'), ('glacial_melt', 'Glacial melt'), ('floods', 'Floods'), ('landslides', 'Landslides')], max_length=255, verbose_name='Driver of displacement'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='focus_area',
            field=models.CharField(choices=[('livelihoods_and_employment', 'Livelihoods and employment'), ('safety_and_security', 'Safety and social security'), ('health', 'Health'), ('education', 'Education'), ('housing_land_and_property', 'Housing, land and property'), ('environment', 'Environment'), ('food_and_water_insecurity', 'Food and water insecurity'), ('social_protection_and_assistance', 'Social protection and assistance')], max_length=255, verbose_name='Focus area'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='type',
            field=models.CharField(choices=[('risk_reduction_and_prevention', 'Risk Reduction and Prevention (DRR, CCA and peacebuilding)'), ('protection_and_assistance_and_durable_solutions', 'Protection and assistance, and durable solutions'), ('strategies_policies_and_legal_frameworks', 'Strengthening policy and legal frameworks'), ('interventions', 'Interventions'), ('policies', 'Policies')], max_length=255, verbose_name='Good practice type'),
        ),
        migrations.DeleteModel(
            name='MediaAndResourceLink',
        ),
    ]
