# Generated by Django 3.2.13 on 2022-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_practice", "0006_alter_goodpractice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodpractice",
            name="implementing_entity",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Implementing entity"
            ),
        ),
    ]
