# Generated by Django 3.2.13 on 2022-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_practice", "0007_goodpractice_implementing_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodpractice",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "risk_reduction_and_prevention",
                        "Risk Reduction and Prevention (DRR, CCA and peacebuilding)",
                    ),
                    (
                        "protection_and_assistance_and_durable_solutions",
                        "Protection and assistance, and durable solutions",
                    ),
                    (
                        "strengthening_policy_and_legal_frameworks",
                        "Strengthening policy and legal frameworks",
                    ),
                    (
                        "governance_capacity_and_institutional_set_up",
                        "Governance capacity and institutional set-up",
                    ),
                    (
                        "displacement_monitoring",
                        "Displacement monitoring (data collection, analysis and systems)",
                    ),
                ],
                max_length=255,
                verbose_name="Good practice type",
            ),
        ),
    ]
