# Generated by Django 3.2.13 on 2022-05-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0007_auto_20220527_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodpractice',
            old_name='drivers_of_dispalcement',
            new_name='drivers_of_displacement',
        ),
    ]
