# Generated by Django 3.2.13 on 2022-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0008_rename_drivers_of_dispalcement_goodpractice_drivers_of_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodpractice',
            name='image',
            field=models.FileField(blank=True, upload_to='good_practice/', verbose_name='Good practice image'),
        ),
    ]
