# Generated by Django 3.2.13 on 2022-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0009_alter_goodpractice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, upload_to='gallery/', verbose_name='Image'),
        ),
    ]
