# Generated by Django 3.2.13 on 2022-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_practice", "0009_alter_goodpractice_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="driversofdisplacement",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="driversofdisplacement",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(blank=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="focusarea",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="focusarea",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="implementing_entity_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Implementing entity",
            ),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="implementing_entity_fr",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Implementing entity",
            ),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="media_and_resource_links_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Media and resource links"
            ),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="media_and_resource_links_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Media and resource links"
            ),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="goodpractice",
            name="title_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Tags"),
        ),
    ]
