# Generated by Django 3.2.13 on 2022-05-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0010_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='good_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_practice', to='good_practice.goodpractice', verbose_name='Good practice'),
        ),
    ]
