# Generated by Django 4.1.4 on 2023-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0024_alter_figureanalysis_year_alter_overview_year'),
        ('good_practice', '0013_alter_goodpractice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpractice',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact name'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='description_of_key_lessons_learned',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Briefly describe the key lessons learned (max 2,000 characters)'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='under_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='what_makes_this_promising_practice',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='What makes this a promising practice? (max 2,000 characters)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='countries',
            field=models.ManyToManyField(related_name='country_good_practice', to='country.country', verbose_name='Country (select from list)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description of the project (max 2,000 characters)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='description_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description of the project (max 2,000 characters)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='description_fr',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description of the project (max 2,000 characters)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='end_year',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Project start year or ongoing'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='implementing_entity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Implementing organisation/entity'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='implementing_entity_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Implementing organisation/entity'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='implementing_entity_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Implementing organisation/entity'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='media_and_resource_links',
            field=models.TextField(blank=True, null=True, verbose_name='Media and resource links (Links to any relevant reports, evaluations or other documents)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='media_and_resource_links_en',
            field=models.TextField(blank=True, null=True, verbose_name='Media and resource links (Links to any relevant reports, evaluations or other documents)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='media_and_resource_links_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Media and resource links (Links to any relevant reports, evaluations or other documents)'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='stage',
            field=models.CharField(blank=True, choices=[('promising', 'Promising'), ('advanced', 'Advanced'), ('successful', 'Successful'), ('unknown', 'Unknown')], max_length=255, null=True, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='start_year',
            field=models.BigIntegerField(verbose_name='Project start year'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of project'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of project'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of project'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='type',
            field=models.CharField(blank=True, choices=[('risk_reduction_and_prevention', 'Risk Reduction and Prevention (DRR, CCA and peacebuilding)'), ('protection_and_assistance_and_durable_solutions', 'Protection and assistance, and durable solutions'), ('strengthening_policy_and_legal_frameworks', 'Strengthening policy and legal frameworks'), ('governance_capacity_and_institutional_set_up', 'Governance capacity and institutional set-up'), ('displacement_monitoring', 'Displacement monitoring (data collection, analysis and systems)'), ('unknown', 'Unknown')], max_length=255, verbose_name='Good practice type'),
        ),
    ]
