# Generated by Django 4.1.4 on 2023-03-07 07:56

from django.db import migrations


class Migration(migrations.Migration):
    help = "Set old good practice under_review to false"

    def update_under_review(apps, schema_editor):
        GoodPractice = apps.get_model('good_practice', 'GoodPractice')
        GoodPractice.objects.update(under_review=False)

    dependencies = [
        ('good_practice', '0014_goodpractice_contact_email_goodpractice_contact_name_and_more'),
    ]

    operations = [
        migrations.RunPython(update_under_review, reverse_code=migrations.RunPython.noop)
    ]
