# Generated by Django 4.1.4 on 2023-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0015_migrate_under_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodpractice',
            name='end_year',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Project end year or ongoing'),
        ),
    ]
