# Generated by Django 4.1.5 on 2023-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_type_to_protection_and_assistance(apps, schema_editor):
        PROTECTION_AND_ASSISTANCE_AND_DURABLE_SOLUTIONS = 'protection_and_assistance_and_durable_solutions'
        PROTECTION_AND_ASSISTANCE = 'protection_and_assistance'

        GoodPractice = apps.get_model('good_practice', 'GoodPractice')
        GoodPractice.objects.filter(
            type=PROTECTION_AND_ASSISTANCE_AND_DURABLE_SOLUTIONS
        ).update(type=PROTECTION_AND_ASSISTANCE)

    dependencies = [
        ('good_practice', '0016_alter_goodpractice_end_year'),
    ]

    operations = [
        migrations.RunPython(
            set_type_to_protection_and_assistance,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='type',
            field=models.CharField(blank=True, choices=[('risk_reduction_and_prevention', 'Risk Reduction and Prevention (DRR, CCA and peacebuilding)'), ('protection_and_assistance', 'Protection and assistance'), ('durable_solutions', 'Durable solutions'), ('strengthening_policy_and_legal_frameworks', 'Strengthening policy and legal frameworks'), ('governance_capacity_and_institutional_set_up', 'Governance capacity and institutional set-up'), ('displacement_monitoring', 'Displacement monitoring (data collection, analysis and systems)'), ('unknown', 'Unknown')], max_length=255, verbose_name='Good practice type'),
        ),
    ]
