# Generated by Django 4.1.5 on 2024-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0018_alter_goodpractice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodpractice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of the project'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description of the project'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description of the project'),
        ),
    ]
