# Generated by Django 4.1.5 on 2024-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_practice', '0019_alter_goodpractice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Success factor')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Success factor')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Success factor')),
            ],
            options={
                'verbose_name': 'Success factor',
                'verbose_name_plural': 'Success factors',
            },
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='success_factor',
            field=models.ManyToManyField(blank=True, null=True, related_name='good_practice', to='good_practice.successfactor', verbose_name='Success factor'),
        ),
    ]
